language: php

php:
    - 7.1

cache:
    directories:
        - vendor

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer update

script:
    - composer validate --strict
